apiVersion: v1
kind: ConfigMap
metadata:
  name: panic-system-config
  namespace: panic-system
data:
  # Database configuration
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "panic_system"
  
  # Redis configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  
  # API configuration
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  DEBUG: "false"
  LOG_LEVEL: "INFO"
  
  # External services
  SMS_PROVIDER: "twilio"
  EMAIL_PROVIDER: "sendgrid"
  PAYMENT_PROVIDER: "stripe"
  
  # Security
  JWT_ALGORITHM: "HS256"
  JWT_ACCESS_TOKEN_EXPIRE_MINUTES: "60"
  JWT_REFRESH_TOKEN_EXPIRE_DAYS: "30"
  
  # Rate limiting
  RATE_LIMIT_ENABLED: "true"
  RATE_LIMIT_REQUESTS_PER_MINUTE: "100"
  
  # Monitoring
  METRICS_ENABLED: "true"
  PROMETHEUS_PORT: "9090"
  
  # Caching
  CACHE_TTL_SECONDS: "300"
  CACHE_MAX_SIZE: "1000"
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: panic-system-config
  namespace: panic-system-staging
data:
  # Database configuration
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "panic_system_staging"
  
  # Redis configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_DB: "1"
  
  # API configuration
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  DEBUG: "true"
  LOG_LEVEL: "DEBUG"
  
  # External services
  SMS_PROVIDER: "twilio"
  EMAIL_PROVIDER: "sendgrid"
  PAYMENT_PROVIDER: "stripe"
  
  # Security
  JWT_ALGORITHM: "HS256"
  JWT_ACCESS_TOKEN_EXPIRE_MINUTES: "60"
  JWT_REFRESH_TOKEN_EXPIRE_DAYS: "30"
  
  # Rate limiting
  RATE_LIMIT_ENABLED: "true"
  RATE_LIMIT_REQUESTS_PER_MINUTE: "1000"
  
  # Monitoring
  METRICS_ENABLED: "true"
  PROMETHEUS_PORT: "9090"
  
  # Caching
  CACHE_TTL_SECONDS: "60"
  CACHE_MAX_SIZE: "100"