global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'panic-system'
    static_configs:
      - targets: ['panic-system:8001']
    scrape_interval: 15s
    metrics_path: '/metrics/prometheus'
    scrape_timeout: 10s

  - job_name: 'panic-system-health'
    static_configs:
      - targets: ['panic-system:8000']
    scrape_interval: 30s
    metrics_path: '/metrics/health'
    scrape_timeout: 10s

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s